name: brat_generator
description: "Bratify - Viral Meme Generator & Custom Aesthetic Photo Frames"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  rate_my_app: ^2.3.1
  http: ^1.2.1
  share_plus: ^11.0.0
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.1.2
  gal: ^2.3.1
  path_provider: ^2.0.11
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/


