class QuoteCategory {
  final String title;
  final String icon;
  final List<String> quotes;

  const QuoteCategory({
    required this.title,
    required this.icon,
    required this.quotes,
  });
}

class QuotesCatalog {
  static const List<QuoteCategory> categories = [
    QuoteCategory(
      title: '🍏 Brat Anthem',
      icon: '🍏',
      quotes: [
        'brat',
        '365 party girl',
        'so transparent',
        'everything is romantic',
        'sympathy is a knife',
        'rewind rewind',
        'von dutch',
        'talk talk to me',
        'i might say something stupid',
        'guess what i wear',
        'girl, so confusing',
        'apple on my tree',
        'b2b all night',
        'mean girls club',
        'spring breakers vibe',
        "it's officially brat summer",
        'club classic on repeat',
        'i think about it all the time',
        'angels dancing in the club',
        'dialing that number again',
        'completely the same but different',
        'sweat tour energy',
        'lime green state of mind',
        'boiler room moment',
        'hyperpop royalty',
      ],
    ),
    QuoteCategory(
      title: '💬 Viral & Relatable',
      icon: '💬',
      quotes: [
        'doing it for the plot',
        'main character energy',
        'delusional in the best way',
        'unhinged and thriving',
        'too iconic to care',
        "it's giving brat",
        'born to party, forced to work',
        'overthinking everything as usual',
        'brat and boujee',
        "it's okay to cry in the club",
        'always chaotic, never boring',
        'living rent free in your head',
        'no thoughts, head empty',
        'certified lover girl',
        'emotionally unavailable right now',
        'soft life era only',
        'vibing and thriving',
        'mentally on permanent vacation',
        'peace over drama every day',
        'eating fries at 3am',
        'hot mess express',
        'chronically online',
        'i survived today',
        'CEO of overthinking',
      ],
    ),
    QuoteCategory(
      title: '🖤 Aesthetic & Mood',
      icon: '🖤',
      quotes: [
        'romanticizing my quiet life',
        'midnight thoughts & blurry lights',
        'vintage soul in a digital world',
        'lost in the right direction',
        'aesthetic overload',
        'polaroid memories never fade',
        'golden hour baby',
        'heavy heart, light head',
        'poetry in motion',
        'shadows and neon signs',
        'quiet luxury & loud music',
        'film grain & cold brew',
        'soft blur memories',
        'faded dreams & neon themes',
        'timeless aesthetic',
        'nostalgia hitting hard',
        'late night drive therapy',
        'analog soul, digital heart',
        '35mm film memories',
        'staring at the ceiling again',
      ],
    ),
    QuoteCategory(
      title: '💅 Savage & Baddie',
      icon: '💅',
      quotes: [
        'not your problem anymore',
        'unbothered, moisturized, happy',
        'upgrade in progress',
        'too glam to give a damn',
        'silence speaks louder than words',
        'zero competition around here',
        'i said what i said',
        'keep watching, baby',
        'built completely different',
        'sorry not sorry',
        'catch flights, not feelings',
        'rare, iconic, untouchable',
        'out of your league',
        'classy, sassy & bad-assy',
        'not everyone has good taste',
        'my own biggest fan',
      ],
    ),
    QuoteCategory(
      title: '👾 Y2K & Cyber',
      icon: '👾',
      quotes: [
        'SYSTEM_ERROR: too iconic',
        'buffering eternal happiness',
        'y2k digital angel',
        'dial-up connection 1999',
        'low battery, high energy',
        'digicam flash in the dark',
        'matrix simulation glitch',
        'cyberpunk city lights',
        'camcorder tape 00:00:00',
        'vhs static dream',
        '2000s flip phone aesthetics',
        'hacker terminal mode',
        'game over, insert coin',
        'pixel perfect fantasy',
      ],
    ),
    QuoteCategory(
      title: '⚡ Party & Rave',
      icon: '⚡',
      quotes: [
        'bass vibrating in my chest',
        'rave until the sun comes up',
        'techno is my therapy',
        'lost in the laser lights',
        'afterparty mood activated',
        'underground sound forever',
        'bpm over 145',
        'neon tears on the dancefloor',
        'dancing through the chaos',
        'electric strobe lights',
        'strobe flash euphoria',
        'the bass dropped and so did i',
      ],
    ),
  ];
}
